services:
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: frontend-web-prod
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./public_html/config/urls.prod.js:/var/www/html/config/urls.js:ro
      - ./virtualhosts/prod/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./logs/prod:/var/www/html/logs
    restart: always
